### ISSUE TITLE
Most of the pages from time.com either fail or can't be displayed in Reader View

### ISSUE THREAD

**Issue by avaida** [mozilla/readability#119]
**Reproducible on**:
Beta 38.0b2-build1 (20150406174117)
Aurora 39.0a2 (2015-04-07)
Nightly 40.0a1 (2015-04-06)

**Sample pages showing this issue**:
* http://time.com/3393418/a-war-photographer-embeds-himself-inside-a-video-game/  (fails only on 38 branch)
* http://time.com/3736616/discover-himalayas-illegal-marijuana-fields/ (Reader View unavailable on all branches)

**Comment by n1k0** [comment]
Fixed in latest master + latest fx-team:

![screen shot 2015-04-07 at 17 57 57](https://cloud.githubusercontent.com/assets/41547/7027441/baf79edc-dd4f-11e4-9edd-846290e9c074.png)

![screen shot 2015-04-07 at 17 59 14](https://cloud.githubusercontent.com/assets/41547/7027459/d6229162-dd4f-11e4-996b-92cfcd9e6a39.png)

**Comment by avaida** [comment]
I'm not sure if it's the same thing, but here's a sample from time.com still showing this issue across branches: http://time.com/3765004/microsoft-project-spartan-browser/.

**Comment by n1k0** [comment]
> I'm not sure if it's the same thing, but here's a sample from time.com still showing this issue across branches: http://time.com/3765004/microsoft-project-spartan-browser/.

This link parses just well using latest master.
